version: "3"
services:
  web:
    container_name: web-nginx
    image: nginx
    ports:
      - "4747:80"
      - "9999:8001"
      - "9998:8002"
      - "2222:8003"
    volumes:
      - ./src:/usr/share/nginx/html/
      - ./config:/etc/nginx/conf.d/
    networks:
      - test-wander 
  php:
    container_name: web-php
    image: 'php:7.2-apache'
    ports:
      - "4748:80"
    volumes:
      - ./src:/var/www/html/
    networks:
      - test-wander

networks:
  test-wander:

# docker-compose up --detach
# docker logs -f --details adc20b2c2480
# docker exec -it web-nginx bash 
# docker exec -it web-php bash 
# https://www.nginx.com/blog/deploying-nginx-plus-as-an-api-gateway-part-1/

